name: techflow_analytics
version: '1.0.0'
config-version: 2

profile: techflow_analytics

require-dbt-version: [">=1.9.0", "<2.0.0"]

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  start_date: '2024-01-01'
  currency: 'USD'

models:
  techflow_analytics:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
      +tags: ['intermediate']
    marts:
      +materialized: table
      +schema: marts
      +tags: ['marts']
      finance:
        +tags: ['finance', 'daily']
        +meta:
          owner: 'finance-team'
      product:
        +tags: ['product', 'daily']
        +meta:
          owner: 'product-team'
      marketing:
        +tags: ['marketing', 'daily']
        +meta:
          owner: 'marketing-team'

seeds:
  techflow_analytics:
    +schema: seeds

snapshots:
  techflow_analytics:
    +schema: snapshots
    +strategy: timestamp
